excluded:
  - Shaders
  - Pods
  - Project/R.generated.swift

disabled_rules:
  - nesting
  - function_parameter_count
  - trailing_whitespace
  - blanket_disable_command

opt_in_rules:
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma

included:
  - MetalInstaFiltersClone

force_cast: warning
force_try:
  severity: warning

type_body_length:
  - 300
  - 400

file_length:
  warning: 500
  error: 800

large_tuple:
  - 3
  - 4

type_name:
  min_length: 4
  max_length:
    warning: 30
    error: 35
  excluded: iPhone

reporter: "xcode"
